version: 2
jobs:
  build:
    docker:
      - image: ros:kinetic-perception
        environment:
          BASH_ENV: "/ros_entrypoint.sh"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt update && apt install -y pylint
      - run:
          name: Linting
          command: pylint --disable=R,C --extension-pkg-whitelist=cv2 src/radlocc_calibration > /tmp/pylint-report.txt
      - store_artifacts:
          path: /tmp/pylint-report.txt
          destination: pylint-report.txt
      
workflows:
  version: 2
  build:
    jobs:
      - build