#!/usr/bin/env python

import rospy

from radlocc_calibration import InteractiveNode, DataSaver

IMAGE_TOPIC = 'image'
LASERSCAN_TOPIC = '/velodyne_points'


if __name__ == '__main__':

    rospy.init_node('radlocc_collect')

    output_dir = rospy.get_param('~output_dir')

    ds = DataSaver(output_dir)

    node = InteractiveNode(data_saver=ds, image_topic=IMAGE_TOPIC, laserscan_topic=LASERSCAN_TOPIC)

    node.start()
